#!/usr/bin/env bash
# pings IP address passed as an argument.

if [[ $1 =~ ^[0-9]{1,3}\. [0-9]{1,3}\. [0-9]{1,3}\. [0-9]{1,3}S ]]
then
	ping -c 5 "SI"
else
	echo "Usage: 5-is_the_host_on_the_network {IP ADDRESS}"
fi
